### ISSUE TITLE
Can you consider dialing back the permissions a little bit?

### ISSUE THREAD

**Issue by LegoStormtroopr** [flatsheet/editdata.org#25]
I fail to see why a simple text/csv editor requires this much access:

> #Personal user data - Full access
> This application will be able to **read and write all user data**. This includes the following:

> * Private email addresses
> * Profile information
> * Followers

> Repositories - Public and private
> This application will be able to **read and write all public and private repository data**. This includes the following:

> * Code
> * Issues
> * Pull requests
> * Wikis
> * Settings
> * Webhooks and services
> * Deploy keys

**Comment by sethvincent** [comment]
Hey, good point. 

It looks like we should be able to drop the `user` scope at least, since we don't really need that.

I guess I went a little "scope happy" with setting up the auth. I'll check and see what the minimum permissions can be and still have everything work.

**Comment by sethvincent** [comment]
ok. I've set it to only ask for the `repo` scope and that's actually all that's necessary. Thanks for pointing that out!
