### ISSUE TITLE
after working with file from GH and then making new file, can only add one column, which gets called "Error"

### ISSUE THREAD

**Issue by ajschumacher** [flatsheet/editdata.org#28]
I want to make a new file! :cry: 

Replicable?

**Comment by sethvincent** [comment]
This is a weird one. So far I'm not able to replicate it.

**Comment by ajschumacher** [comment]
hmm. anyway I resolved by doing a hard re-load. not a prob?

**Comment by sethvincent** [comment]
I just pushed a fix that I think solves this issue. Or at least solves a related issue with the editor remembering columns from previous datasets. Closing for now. Definitely reopen if the problem persists.
